# Generated by Django 5.1.1 on 2024-10-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_categorys_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='API.categorys'),
        ),
    ]
